name: Build and Push Custom Caddy Image

on:
  workflow_dispatch:

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gomplate
        shell:  bash
        env:
          GOMPLATE_VERSION: "v5.2.0"
          BASE_URL: "https://github.com/hairyhenderson/gomplate"
          BIN_NAME: "gomplate_linux-amd64"
        run: |
          TEMP_DIR="${{ runner.temp }}/gomplate"
          BIN_FILE="$TEMP_DIR/gomplate"
          mkdir -p "$TEMP_DIR"
          DOWNLOAD_URL="${BASE_URL}/releases/download/${GOMPLATE_VERSION}/${BIN_NAME}"
          curl -sSL "${DOWNLOAD_URL}" -o "$BIN_FILE"
          chmod +x "$BIN_FILE"
          echo "$TEMP_DIR" >> $GITHUB_PATH

      - name: Checkout source code
        uses: actions/checkout@v7

      - name: load caddy version
        run: gomplate -c config.yaml -i 'VERSION={{ .config.caddy.version }}' >> $GITHUB_ENV

      - name: generate DockerFile
        run: gomplate -c config.yaml -f caddy/Dockerfile.tmpl -o caddy/Dockerfile

      - name: Build caddy Container image
        id: build-image
        uses: redhat-actions/buildah-build@v3
        working-directory: ./caddy
        with:
          image: caddy
          tags: latest ${{ env.VERSION }}
          containerfiles: |
            ./Dockerfile
          platforms: linux/amd64
          oci: true

      - name: Push image to ghcr.io
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
